#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the freqQuery function below.
def freqQuery(queries):
    d = []
    for q in queries:
        inp = q
        if inp[0] == 1:
            d.append(inp[1])
        elif inp[0] == 2:
            if inp[1] in d:
                d.remove(inp[1])
        elif inp[0] == 3:
            flag = False
            for i in d:
                if d.count(i) == inp[1]:
                    flag = True
                    break
            if flag: print(1)
            else: print(0)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    print (queries)
    ans = freqQuery(queries)

    fptr.write('\n'.join(map(str, ans)))
    fptr.write('\n')

    fptr.close()
